### ISSUE TITLE
really 140 Ohm Resistor?

### ISSUE THREAD

**Issue by Liriel-666** [ste2425/PSP-Consolizer#10]
really 140 Ohm Resistor for the LED? Thats a Really unusale Resistor and hard to find.
Most sell only 130 or 150 Ohm als normal.
140 ohm as smd yeah easy to find

**Comment by ste2425** [comment]
Hey, to be honest when i designed the PCB i didn't know any better! I think i arrived at value either from a guide i followed or some resistor calculator.

If there is a better value you can recommend i will gladly update it to help others.

**Comment by ste2425** [comment]
Closing this. The schematic being reference is for e older Arduino version. The newer ESP version doesn’t have such issues, I don’t think. 

Feel free to re-open and Ofer a PR to fix if this issue still exists.
