### ISSUE TITLE
Pressing X Puts the PSP to Sleep?

### ISSUE THREAD

**Issue by Grae87** [ste2425/PSP-Consolizer#12]
Hi, sorry if this is something basic, but everything seems to work except the X button. When I press it, the console goes to sleep.

I've checked continuity with all the points. I can't find any bridging or cold solder points.
No issues came up with the Arduino flash either.

Can anyone help?

**Comment by ste2425** [comment]
The FFC which controls the PSP’s power button is on the same connector as the X button (and all the others on that side for that matter) 

My first port of call would be to verify the FFC is correctly seated at both ends. Also ensure is is not obviously damaged. 

When building this many times I had nudged one of the cables causing behaviour like this. 

Once one of them had an internal break causing similar behaviour but that seems rarer from my experience

**Comment by ste2425** [comment]
Closing this as stale. Please re-open if any new information is available.
